[project]
name = "dog_breed_finder"
version = "1.0.0"
description = "A web application to find the perfect dog breed."
authors = [
    { name = "Micah van der Horst" }
]
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
